server:
  port: 9090
logging:
  level:
    root: info  
# Oracle #
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: dbexamen
    password: 1234567
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    web:
      pageable:
        page-parameter: p
        size-parameter: limit

  
        
